spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classroom?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jdbc:
    template:
      query-timeout: 30

server:
  port: 8080
